accounts/urls.py
"""Name: Ryan Kirkbtride
   Date: 3/1/23
   Class: CIS218 Barnes

"""


from django.urls import path

from .views import SignUpView

urlpatterns = [path("signup/", SignUpView.as_view(), name="signup")]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("restaurant.urls")),
]

restaurant/urls.py
from django.urls import path
from .views import (
    RestaurantListView,
    RestaurantDetailView,
    ReviewCreateView,
    ReviewDetailView,
    ReviewEditView,
    ReviewDeleteView,
)

urlpatterns = [
    path("Review/new/", ReviewCreateView.as_view(), name="review_new"),
    path("Review/<int:pk>/", ReviewDetailView.as_view(), name="review_detail"),
    path("Review/<int:pk>/edit/", ReviewEditView.as_view(), name="review_edit"),
    path("Review/<int:pk>/delete/", ReviewDeleteView.as_view(), name="review_delete"),
    path(
        "Restaurant/<int:pk>/",
        RestaurantDetailView.as_view(),
        name="restaurant_detail",
    ),
    path("", RestaurantListView.as_view(), name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

restaurant/models.py
from django.db import models
from django.urls import reverse


class Restaurant(models.Model):
    """Restaurant model class"""

    restaurant_name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String method"""
        return self.restaurant_name

    def get_absolute_url(self):
        """Get absolute URL"""
        return reverse("restaurant_detail", kwargs={"pk": self.pk})


class Review(models.Model):
    """Review model class"""

    restaurant = models.ForeignKey(
        # "restaurant_name",
        Restaurant,  # Trying something New
        on_delete=models.CASCADE,
        related_name="reviews",
    )

    author = models.ForeignKey(  # changed to author
        "auth.user",
        on_delete=models.CASCADE,
        related_name="user",
    )

    review_title = models.CharField(max_length=200)
    email = models.EmailField()
    body = models.TextField(max_length=500)
    rating = models.IntegerField(default=3)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String method"""
        return self.review_title

    def get_absolute_url(self):
        return reverse("review_detail", kwargs={"pk": self.pk})

accounts/views.py
from django.contrib.auth.forms import UserCreationForm

"""Name: Ryan Kirkbtride
   Date: 3/1/23
   Class: CIS218 Barnes
"""
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    """Sign up View"""

    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

restaurant/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Restaurant, Review


class RestaurantListView(ListView):
    """Restaurant List View"""

    model = Restaurant
    template_name = "home.html"


class RestaurantDetailView(DetailView):
    """Review list view"""

    model = Restaurant
    template_name = "restaurant_detail.html"


class ReviewCreateView(LoginRequiredMixin, CreateView):
    """Review Create View"""

    model = Review
    template_name = "review_new.html"
    fields = ["restaurant", "rating", "author", "body"]

    def get_initial(self):
        """Get initial form data"""
        # Get the result of calling the parent method
        initial_data = super().get_initial()
        # Add the author so it is the request user
        initial_data["author"] = self.request.user
        # return the data


class ReviewDetailView(DetailView):
    """ "Review Detail View"""

    model = Review
    template_name = "review_detail.html"


class ReviewEditView(LoginRequiredMixin, UpdateView):
    """Review edit View"""

    model = Review
    template_name = "review_edit.html"
    fields = ["rating", "body"]


class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    """Review delete View"""

    model = Review
    template_name = "review_delete.html"
    success_url = reverse_lazy("home")

templates/base.html
{% load static %}
{% comment "" %}
Name: Ryan Kirkbride
Date: 3/1/2023
Class: CIS218-Barnes
{% endcomment %}
<html>
  <head>
    <title>Populace Restaurant Reviews</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    <div>
      <header>
        <div class="nav-left">
          <h1><a href="{% url 'home' %}">Populace Restaurant Reviews</a></h1>
        </div>
      </header>
      <div class="nav-right">
        {% if user.is_authenticated %}
          <p>Hi {{ user.username }}!&nbsp;</p>
          <p><button type="button" class="btn border1 border111"><a href="{% url 'logout' %}">Logout</a></button></p>
          <p><button type="button" class="btn border1 border111"><a href="{% url 'review_new' %}">Add Review</a></button></p>
        {% else %}
          <p> You are not logged in.&nbsp;</p>
          <p>
            <button type="button" class="btn border1 border111"><a href="{% url 'login' %}">Login</a></button>
            <button type="button" class="btn border1 border111"><a href="{% url 'signup' %}">Sign Up</a></button>
            </p>
        {% endif %}
      </div>
      <div>
        {% block content %}
        {% endblock content %}
      </div>

    </div>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% comment "" %}
Name: Ryan Kirkbride
Date: 3/1/2023
Class: CIS218-Barnes
{% endcomment %}
{% block content %}
  {% for restaurant in restaurant_list %}
    <div class="post-entry">
      <h2><a href="{% url 'restaurant_detail' restaurant.pk %}">{{ restaurant.restaurant_name }}</a></h2>
      <p></p>
    </div>
  {% endfor %}
{% endblock content %}

templates/restaurant_detail.html
{% extends 'base.html' %}
{% comment "" %}
Name: Ryan Kirkbride
Date: 3/1/2023
Class: CIS218-Barnes
{% endcomment %}
{% block content %}
  <div class="post-entry">
    <h2><a>{{ restaurant.restaurant_name }}</a></h2>

  </div>

  <h3>Reviews for this restaurant:</h3>
    {% for restaurant in restaurant.reviews.all  %}
    <div class="post-entry">
      <p>{{ restaurant.author }} - {{ restaurant.rating}}-star - Created {{ restaurant.created}} </p>
        <p>{{restaurant.body}}</p>
        <button type="button" class="btn border1 border111"><a href="{% url 'review_detail' restaurant.pk %}">Read Review</a></button>
    </div>
    {% endfor %}
{% endblock content %}

templates/review_delete.html
{% extends 'base.html' %}
{% comment "" %}
Name: Ryan Kirkbride
Date: 3/1/2023
Class: CIS218-Barnes
{% endcomment %}
{% block content %}
  <h1>Delete Review</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete {{review.restaurant}}&nbsp;review?</p>
    <input type="submit" value="Confirm">
  <form>
{% endblock content %}

templates/review_detail.html
{% extends 'base.html' %}
{% comment "" %}
Name: Ryan Kirkbride
Date: 3/1/2023
Class: CIS218-Barnes
{% endcomment %}
{% block content %}
<div class="post-entry">
  <p>User: {{ review.author }}</p>
  <p>Rating: {{ review.rating }}</p>
  <p>Reviw: {{ review.body }}</p>
  <p>Created: {{ review.created }}</p>
  <p>Updated: {{ review.updated }}</p>
</div>
{% if user.is_authenticated %}
  <button type="button" class="btn border1 border111"><a href="{% url 'review_edit' review.pk %}">Edit Review</a></button>
  <button type="button" class="btn border1 border111"><a href="{% url 'review_delete' review.pk %}">Delete Review</a></button>

{% endif %}
{% endblock content %}

templates/review_edit.html
{% extends 'base.html' %}
{% comment "" %}
Name: Ryan Kirkbride
Date: 3/1/2023
Class: CIS218-Barnes
{% endcomment %}
{% block content %}
  <h1>Edit review</h1>
  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
  <input type="submit" value="Update">
  </form>
{% endblock content %}

templates/review_new.html
{% extends 'base.html' %}
{% comment "" %}
Name: Ryan Kirkbride
Date: 3/1/2023
Class: CIS218-Barnes
{% endcomment %}
{% block content %}
  <h1>New Review</h1>
  <form action"" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
{% endblock content %}